import {EMPLOYEE_SCHEDULES,ADMIN_SURNAME_ROLES,normalizeName,scheduleFor,type EmployeeSchedule} from "./employeeSchedules";
export const WEEKDAYS=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
export type Weekday=typeof WEEKDAYS[number]; export type ScheduleType="FULL DAY"|"MORNING"|"AFTERNOON";
export type DailySchedule={start:number;end:number;type:ScheduleType}; export type Schedule=Record<Weekday,DailySchedule|null>; export type Grid=unknown[][];
export type CheckRow={dateLabel:string;actualWeekday:string;remarks:string;hasIssue:boolean;status:"ISSUE"|"WFH"|"ABSENT"|"VERIFIED";wfh:boolean;absent:boolean;wfhVerified:boolean;absentVerified:boolean};
export type RunResult={rows:CheckRow[];totalDays:number;issueCount:number;wfhCount:number;absentCount:number;employeeId?:string;employeeName:string;role:string;schedule:EmployeeSchedule;remarksColumnFound:boolean};
export const DEFAULT_ADMIN_SCHEDULE:Schedule={monday:{start:480,end:1020,type:"FULL DAY"},tuesday:{start:480,end:1020,type:"FULL DAY"},wednesday:{start:480,end:1020,type:"FULL DAY"},thursday:{start:480,end:1020,type:"FULL DAY"},friday:{start:480,end:1020,type:"FULL DAY"},saturday:null,sunday:null};
function asDate(v:unknown):Date|null{if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;if(typeof v==="number"){const d=new Date(Math.round((v-25569)*86400*1000));return Number.isNaN(d.getTime())?null:d}if(typeof v==="string"){const d=new Date(v);return Number.isNaN(d.getTime())?null:d}return null}
function key(v:unknown){const d=asDate(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`:null}
function weekday(d:Date):Weekday{return WEEKDAYS[(d.getDay()+6)%7]}
function text(v:unknown){return String(v??"").trim()}
function firstDateColumn(grid:Grid){for(let c=0;c<Math.max(...grid.slice(0,5).map(r=>r.length),0);c++){if(grid.slice(0,20).some(r=>key(r[c])!==null))return c}return -1}
function findHeader(grid:Grid,names:string[]){const wanted=names.map(x=>x.toLowerCase());for(const row of grid.slice(0,20)){const i=row.findIndex(x=>wanted.includes(text(x).toLowerCase()));if(i>=0)return i}return -1}
function parseDtr(grid:Grid){let dateCol=findHeader(grid,["date","dtr date"]);if(dateCol<0)dateCol=firstDateColumn(grid);let typeCol=findHeader(grid,["c/in","c/out"]);if(typeCol<0){for(let c=0;c<8;c++)if(grid.slice(0,20).some(r=>/^(c\/in|c\/out)$/i.test(text(r[c])))){typeCol=c;break}}
let remarksCol=findHeader(grid,["remarks","remark","remarks / status","status"]);if(remarksCol<0)remarksCol=7;return{dateCol,typeCol,remarksCol}}
function parseBio(grid:Grid){let timeCol=findHeader(grid,["timestamp","datetime","date/time","time"]);let typeCol=findHeader(grid,["c/in or c/out","c/in","c/out","type"]);let empCol=findHeader(grid,["employee no.","employee no","employee number","emp no","id"]);if(timeCol<0)timeCol=1;if(typeCol<0)typeCol=2;if(empCol<0)empCol=0;return{timeCol,typeCol,empCol}}
function extractDtrEmployee(grid:Grid){for(const row of grid.slice(0,5))for(const v of row){const m=text(v).match(/^\s*\d+\s*-\s*(.+)$/);if(m)return normalizeName(m[1].replace(/,\s*.*/,""))}return ""}
function dtrDateMap(grid:Grid,dateCol:number,startDate:Date,endDate:Date){const map=new Map<string,unknown[]>();let year=startDate.getFullYear();for(const row of grid){const direct=key(row[dateCol]);if(direct){const dt=asDate(row[dateCol])!;year=dt.getFullYear();map.set(direct,row);continue}const n=text(row[1]),label=text(row[2]);if(/^\d+$/.test(n)&&label){const parsed=new Date(`${label} ${year}`);if(!Number.isNaN(parsed.getTime()))map.set(key(parsed)!,row)}}return map}
export function resolveEmployee(surname:string,dtrGrid:Grid,bioGrid:Grid){const target=normalizeName(surname);if(target==="RAMOS"||target==="RAMOS, H"||target==="RAMOS, J"){if(target==="RAMOS")throw new Error("RAMOS has two admins. Enter RAMOS, H or RAMOS, J.");return{name:target,role:"ADMIN"}}
const dtrName=extractDtrEmployee(dtrGrid);const scheduleMatches=Object.keys(EMPLOYEE_SCHEDULES).filter(n=>n===target||n.includes(target));const name=dtrName||scheduleMatches[0]||target;return{name,role:ADMIN_SURNAME_ROLES[name]??ADMIN_SURNAME_ROLES[target]??"REGULAR"}}
function timeFromDate(v:unknown){const d=asDate(v);return d?d.getHours()*60+d.getMinutes():null}
export function runCheck({dtrGrid,bioGrid,surname,startDate,endDate}:{dtrGrid:Grid;bioGrid:Grid;surname:string;startDate:Date;endDate:Date}):RunResult{
 const d=parseDtr(dtrGrid),bcols=parseBio(bioGrid),employee=resolveEmployee(surname,dtrGrid,bioGrid),target=normalizeName(employee.name),bio=new Map<string,{cin:number|null;cout:number|null;employee?:string}>(),dtrRows=dtrDateMap(dtrGrid,d.dateCol,startDate,endDate);
 for(const row of bioGrid){const dt=asDate(row[bcols.timeCol]);if(!dt)continue;const k=key(dt)!;const cur=bio.get(k)??{cin:null,cout:null};const typ=text(row[bcols.typeCol]).toLowerCase(),m=timeFromDate(dt)!;if(typ.includes("out"))cur.cout=cur.cout===null?m:Math.max(cur.cout,m);else if(typ.includes("in"))cur.cin=cur.cin===null?m:Math.min(cur.cin,m);if(row[bcols.empCol]!=null&&text(row[bcols.empCol]))cur.employee=text(row[bcols.empCol]);bio.set(k,cur)}
 const rows:CheckRow[]=[];const cursor=new Date(startDate);let totalDays=0;const employeeSchedule=scheduleFor(target)??(employee.role==="ADMIN"?DEFAULT_ADMIN_SCHEDULE:DEFAULT_ADMIN_SCHEDULE) as EmployeeSchedule;
 while(cursor<=endDate){const k=key(cursor)!;totalDays++;const day=weekday(cursor),plan=employeeSchedule[day]??null,dtrRow=dtrRows.get(k);let original=dtrRow?text(dtrRow[d.remarksCol]):"";const label=dtrRow?text(dtrRow[d.dateCol]):"";if(dtrRow&&!asDate(dtrRow[d.dateCol]))original=[label,original].filter(Boolean).join(" ");const upper=original.toUpperCase();const wfh=/\bWFH\b|WORK FROM HOME/.test(upper);const absent=/\bABSENT\b/.test(upper);const bb=bio.get(k);const issues:string[]=[];
 if(wfh&&!bb){}else if(absent&&!bb){}else if(absent&&bb)issues.push("ABSENT with biometric attendance");else if(plan){if(!bb?.cin)issues.push("Missing C/In");if(!bb?.cout)issues.push("Missing C/Out");if(bb?.cin!=null&&bb.cin>plan.start)issues.push("LATE");if(bb?.cout!=null&&bb.cout<plan.end)issues.push("U.T.");if(/\bLATE\b/.test(upper)&&bb?.cin!=null&&bb.cin<=plan.start)issues.push("Incorrect DTR LATE remark");if(/\bU\.?T\.?\b|UNDERTIME/.test(upper)&&bb?.cout!=null&&bb.cout>=plan.end)issues.push("Incorrect DTR U.T. remark");}else if(bb)issues.push("Attendance on NO WORK day");
 const status=issues.length?"ISSUE":wfh?"WFH":absent?"ABSENT":"VERIFIED";rows.push({dateLabel:k,actualWeekday:day,remarks:issues.length?issues.join(" • "):original||"Verified",hasIssue:issues.length>0,status,wfh,absent,wfhVerified:false,absentVerified:false});cursor.setDate(cursor.getDate()+1)}
 return{rows,totalDays,issueCount:rows.filter(r=>r.hasIssue).length,wfhCount:rows.filter(r=>r.wfh).length,absentCount:rows.filter(r=>r.absent).length,employeeId:Array.from(bio.values()).find(v=>v.employee)?.employee,employeeName:target,role:employee.role,schedule:employeeSchedule,remarksColumnFound:d.remarksCol>=0};
}