import {EMPLOYEE_SCHEDULES,ADMIN_SURNAME_ROLES,normalizeName,scheduleFor,type EmployeeSchedule} from "./employeeSchedules";
export const WEEKDAYS=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
export type Weekday=typeof WEEKDAYS[number]; export type ScheduleType="FULL DAY"|"MORNING"|"AFTERNOON";
export type DailySchedule={start:number;end:number;type:ScheduleType}; export type Schedule=Record<Weekday,DailySchedule|null>; export type Grid=unknown[][];
export type CheckRow={dateLabel:string;actualWeekday:string;remarks:string;hasIssue:boolean;status:"ISSUE"|"WFH"|"ABSENT"|"VERIFIED";wfh:boolean;absent:boolean;wfhVerified:boolean;absentVerified:boolean};
export type RunResult={rows:CheckRow[];totalDays:number;issueCount:number;wfhCount:number;absentCount:number;employeeId?:string;employeeName:string;role:string;schedule:EmployeeSchedule;remarksColumnFound:boolean};
export const DEFAULT_ADMIN_SCHEDULE:Schedule={monday:{start:480,end:1020,type:"FULL DAY"},tuesday:{start:480,end:1020,type:"FULL DAY"},wednesday:{start:480,end:1020,type:"FULL DAY"},thursday:{start:480,end:1020,type:"FULL DAY"},friday:{start:480,end:1020,type:"FULL DAY"},saturday:null,sunday:null};
function asDate(v:unknown):Date|null{if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;if(typeof v==="number"){const d=new Date(Math.round((v-25569)*86400*1000));return Number.isNaN(d.getTime())?null:d}if(typeof v==="string"){const d=new Date(v);return Number.isNaN(d.getTime())?null:d}return null}
function key(v:unknown){const d=asDate(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`:null}
function weekday(d:Date):Weekday{return WEEKDAYS[(d.getDay()+6)%7]}
function header(grid:Grid,names:string[]){const wanted=names.map(x=>x.toLowerCase());for(const row of grid.slice(0,20)){const i=row.findIndex(x=>wanted.includes(String(x??"").trim().toLowerCase()));if(i>=0)return i}return -1}
function headerRow(grid:Grid){for(let i=0;i<Math.min(20,grid.length);i++){const s=grid[i].map(x=>String(x??"").toLowerCase()).join(" ");if(/date|employee|timestamp|time|remarks|remark|status|surname|name/.test(s))return i}return 0}
function timeFromDate(v:unknown){const d=asDate(v);return d?d.getHours()*60+d.getMinutes():null}
function text(v:unknown){return String(v??"").trim()}
function findEmployee(grid:Grid,surname:string){const sr=header(grid,["surname","employee name","employee","name","employee surname"]);if(sr<0)return null;const target=normalizeName(surname);const candidates=new Set<string>();for(const row of grid.slice(headerRow(grid)+1)){const n=normalizeName(text(row[sr]));if(n&&n.includes(target))candidates.add(n)}return candidates.size===1?[...candidates][0]:candidates.size>1?null:null}
export function resolveEmployee(surname:string,dtrGrid:Grid,bioGrid:Grid){const target=normalizeName(surname);const scheduleMatches=Object.keys(EMPLOYEE_SCHEDULES).filter(n=>n===target||n.includes(target));const d=findEmployee(dtrGrid,target);const b=findEmployee(bioGrid,target);const names=[...new Set([...(d?[d]:[]),...(b?[b]:[]),...scheduleMatches])];if(target.startsWith("RAMOS")){if(target==="RAMOS, H"||target==="RAMOS, J")return {name:target,role:"ADMIN"};return {name:"",role:"",ambiguous:true,candidates:["RAMOS, H","RAMOS, J"]}}
if(names.length===1)return {name:names[0],role:ADMIN_SURNAME_ROLES[names[0]]??"REGULAR"};
if(ADMIN_SURNAME_ROLES[target])return {name:target,role:"ADMIN"};
return {name:target,role:"REGULAR"};}
export function runCheck({dtrGrid,bioGrid,surname,startDate,endDate}:{dtrGrid:Grid;bioGrid:Grid;surname:string;startDate:Date;endDate:Date}):RunResult{
 const dr=headerRow(dtrGrid),br=headerRow(bioGrid),dDate=header(dtrGrid,["date","dtr date"]),remarks=header(dtrGrid,["remarks","remark","remarks / status","status"]),dName=header(dtrGrid,["surname","employee name","employee","name"]),bTime=header(bioGrid,["timestamp","datetime","date/time","time"]),bType=header(bioGrid,["c/in or c/out","c/in","c/out","type"]),bEmp=header(bioGrid,["employee no.","employee no","employee number","emp no","id"]),bName=header(bioGrid,["surname","employee name","employee","name"]);
 const employee=resolveEmployee(surname,dtrGrid,bioGrid);if(employee.ambiguous)throw new Error("RAMOS has two admins. Enter RAMOS, H or RAMOS, J.");
 const target=normalizeName(employee.name||surname);const bio=new Map<string,{cin:number|null;cout:number|null;employee?:string}>();
 for(const row of bioGrid.slice(br+1)){if(bName>=0&&!normalizeName(text(row[bName])).includes(target))continue;const d=asDate(bTime>=0?row[bTime]:row[0]);if(!d)continue;const k=key(d)!;const cur=bio.get(k)??{cin:null,cout:null};const typ=text(bType>=0?row[bType]:"").toLowerCase(),m=timeFromDate(d)!;if(typ.includes("out"))cur.cout=cur.cout===null?m:Math.max(cur.cout,m);else cur.cin=cur.cin===null?m:Math.min(cur.cin,m);if(bEmp>=0&&row[bEmp]!=null)cur.employee=text(row[bEmp]);bio.set(k,cur)}
 const rows:CheckRow[]=[];const cursor=new Date(startDate);let totalDays=0;const employeeSchedule=scheduleFor(target)??(employee.role==="ADMIN"?{monday:{start:480,end:1020},tuesday:{start:480,end:1020},wednesday:{start:480,end:1020},thursday:{start:480,end:1020},friday:{start:480,end:1020},saturday:null,sunday:null}:DEFAULT_ADMIN_SCHEDULE) as EmployeeSchedule;
 while(cursor<=endDate){const k=key(cursor)!;totalDays++;const day=weekday(cursor),plan=employeeSchedule[day];const dtr=dtrGrid.slice(dr+1).find(r=>(dName>=0&&!normalizeName(text(r[dName]).toString()).includes(target)?false:key(dDate>=0?r[dDate]:r[0])===k));const original=remarks>=0&&dtr?text(dtr[remarks]):"";const upper=original.toUpperCase();const wfh=/\bWFH\b|WORK FROM HOME/.test(upper);const absent=/\bABSENT\b/.test(upper);const b=bio.get(k);const issues:string[]=[];
 if(wfh&&!b){ } else if(absent&&!b){} else if(absent&&b)issues.push("ABSENT with biometric attendance"); else if(plan){if(!b?.cin)issues.push("Missing C/In");if(!b?.cout)issues.push("Missing C/Out");if(b?.cin!=null&&b.cin>plan.start)issues.push("LATE");if(b?.cout!=null&&b.cout<plan.end)issues.push("U.T.");if(/\bLATE\b/.test(upper)&&b?.cin!=null&&b.cin<=plan.start)issues.push("Incorrect DTR LATE remark");if(/\bU\.?T\.?\b/.test(upper)&&b?.cout!=null&&b.cout>=plan.end)issues.push("Incorrect DTR U.T. remark");}else if(b)issues.push("Attendance on NO WORK day");
 const status=issues.length?"ISSUE":wfh?"WFH":absent?"ABSENT":"VERIFIED";rows.push({dateLabel:k,actualWeekday:day,remarks:issues.length?issues.join(" • "):original||"Verified",hasIssue:issues.length>0,status,wfh,absent,wfhVerified:false,absentVerified:false});cursor.setDate(cursor.getDate()+1)}
 return {rows,totalDays,issueCount:rows.filter(r=>r.hasIssue).length,wfhCount:rows.filter(r=>r.wfh).length,absentCount:rows.filter(r=>r.absent).length,employeeId:Array.from(bio.values()).find(v=>v.employee)?.employee,employeeName:target,role:employee.role,schedule:employeeSchedule,remarksColumnFound:remarks>=0};
}