import {useMemo,useState} from "react";
import {Button} from "./components/ui/button";import {Input} from "./components/ui/input";import {Label} from "./components/ui/label";
import {runCheck,type CheckRow,type RunResult} from "./lib/payroll/engine";import {downloadIssuesReport,readWorkbookGrid} from "./lib/payroll/workbook";
const ADMIN_HINT="Admin schedules use 8:00 AM–5:00 PM Monday–Friday. Regular employees use the stored teacher schedule.";
function FileDrop({label,file,onFile}:{label:string;file:File|null;onFile:(f:File|null)=>void}){return <div className="drop"><div><b>{label}</b><p>{file?file.name:"Excel or CSV file"}</p></div><div>{file&&<Button variant="ghost" size="sm" onClick={()=>onFile(null)}>Clear</Button>}<Button variant="secondary" size="sm" onClick={()=>document.getElementById(`file-${label}`)?.click()}>Choose file</Button></div><input id={`file-${label}`} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>onFile(e.target.files?.[0]??null)}/></div>}
function Status({kind}:{kind:CheckRow["status"]}){return <span className={`badge badge-${kind.toLowerCase()}`}>{kind}</span>}
export function PayrollCheckerPage(){const[surname,setSurname]=useState(""),[startDate,setStartDate]=useState("2026-06-26"),[endDate,setEndDate]=useState("2026-07-15"),[dtrFile,setDtrFile]=useState<File|null>(null),[bioFile,setBioFile]=useState<File|null>(null),[result,setResult]=useState<RunResult|null>(null),[error,setError]=useState<string|null>(null),[running,setRunning]=useState(false),[filter,setFilter]=useState("ALL"),[checks,setChecks]=useState<Record<string,boolean>>({});
 const rows=useMemo(()=>{if(!result)return[];if(filter==="ALL")return result.rows;return result.rows.filter(r=>r.status===filter||(filter==="UNVERIFIED"&&((r.wfh&&!checks[`wfh-${r.dateLabel}`])||(r.absent&&!checks[`abs-${r.dateLabel}`]))));},[result,filter,checks]);
 async function handleRun(){setError(null);if(!surname.trim())return setError("Enter the employee surname. For Ramos, use RAMOS, H or RAMOS, J.");if(!dtrFile||!bioFile)return setError("Upload both the DTR and biometrics files.");const from=new Date(`${startDate}T00:00:00`),to=new Date(`${endDate}T00:00:00`);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)return setError("Enter a valid date range.");setRunning(true);try{const[dtr,bio]=await Promise.all([readWorkbookGrid(dtrFile),readWorkbookGrid(bioFile)]);const r=runCheck({dtrGrid:dtr,bioGrid:bio,surname,startDate:from,endDate:to});setResult(r);setChecks(Object.fromEntries(r.rows.map(x=>[`wfh-${x.dateLabel}`,false]).concat(r.rows.map(x=>[`abs-${x.dateLabel}`,false]))));}catch(e){setResult(null);setError(e instanceof Error?e.message:"Could not analyze the files.")}finally{setRunning(false)}}
 function toggle(row:CheckRow){const key=`${row.wfh?"wfh":"abs"}-${row.dateLabel}`;setChecks(p=>({...p,[key]:!p[key]}));}
 function exportFile(){if(!result)return;const final={...result,rows:result.rows.map(r=>({...r,wfhVerified:!!checks[`wfh-${r.dateLabel}`],absentVerified:!!checks[`abs-${r.dateLabel}`]}))};downloadIssuesReport(final,`${result.employeeName.replace(/[^A-Z0-9, _-]/gi,"")||"EMPLOYEE"}_attendance.xlsx`)}
 return <main><header><div className="wrap"><small>ATTENDANCE AUDIT</small><h1>Payroll Checker</h1><p>Compare the DTR and biometrics against the employee's real schedule. Files are processed in your browser.</p></div></header><div className="wrap content">
 <section><div className="section-head"><div><h2>Employee & period</h2><p>{ADMIN_HINT}</p></div></div><div className="grid3"><div><Label htmlFor="surname">Surname</Label><Input id="surname" value={surname} placeholder="BAUTISTA" onChange={e=>setSurname(e.target.value)}/></div><div><Label htmlFor="start">Start date</Label><Input id="start" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div><Label htmlFor="end">End date</Label><Input id="end" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div></div></section>
 <section><h2>Files</h2><div className="files"><FileDrop label="DTR workbook" file={dtrFile} onFile={setDtrFile}/><FileDrop label="Biometrics export" file={bioFile} onFile={setBioFile}/></div>{error&&<p className="error">{error}</p>}<div className="actions"><Button onClick={handleRun} disabled={running}>{running?"Analyzing…":"Analyze attendance"}</Button>{result&&<Button variant="secondary" onClick={exportFile}>Export Excel</Button>}</div></section>
 {result&&<><section><div className="employee-card"><div><small>EMPLOYEE</small><h2>{result.employeeName}</h2><p>{result.role} · ID {result.employeeId??"Not found in biometrics"}</p></div><div className="stats"><div><strong>{result.totalDays}</strong><span>DAYS</span></div><div><strong className="red">{result.issueCount}</strong><span>ISSUES</span></div><div><strong>{result.wfhCount}</strong><span>WFH</span></div><div><strong>{result.absentCount}</strong><span>ABSENT</span></div></div></div></section>
 <section><div className="filters">{["ALL","ISSUE","WFH","ABSENT","VERIFIED","UNVERIFIED"].map(x=><button key={x} className={filter===x?"filter active":"filter"} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="results"><table><thead><tr><th>Date</th><th>Day</th><th>Status</th><th>Issues / Remarks</th><th>Verify</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.dateLabel}-${i}`} className={r.hasIssue?"issue":""}><td>{r.dateLabel}</td><td>{r.actualWeekday}</td><td><Status kind={r.status}/></td><td>{r.remarks}</td><td>{(r.wfh||r.absent)&&<button className={`check ${checks[`${r.wfh?"wfh":"abs"}-${r.dateLabel}`]?"checked":""}`} onClick={()=>toggle(r)} aria-label="Verify">✓</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No records for this filter.</p>}</div></section></>}
 <footer>Actual calendar dates determine weekdays. WFH/ABSENT without biometrics are not issues; they require manual verification. An ABSENT record with biometric attendance is flagged.</footer></div></main>}
