import {useMemo,useState} from "react";
import {Button} from "./components/ui/button";
import {Input} from "./components/ui/input";
import {Label} from "./components/ui/label";
import {runCheck,type CheckRow,type RunResult} from "./lib/payroll/engine";
import {downloadIssuesReport,readWorkbookGrid} from "./lib/payroll/workbook";
import {ADMIN_SURNAME_ROLES,EMPLOYEE_SCHEDULES,normalizeName} from "./lib/payroll/employeeSchedules";

const ADMIN_HINT="Admins use 8:00 AM–5:00 PM Monday–Friday. Regular employees use the stored employee schedule. For Ramos, enter RAMOS, H or RAMOS, J.";
const EMPLOYEES=[...new Set([...Object.keys(EMPLOYEE_SCHEDULES),...Object.keys(ADMIN_SURNAME_ROLES)])].sort((a,b)=>a.localeCompare(b));

function Workflow({step}:{step:number}){const items=["Employee","Date Range","Upload","Results"];return <nav className="workflow" aria-label="Payroll checker workflow">{items.map((item,i)=><div key={item} className={`workflow-step ${i===step?"current":""} ${i<step?"done":""}`}><span>{i<step?"✓":i+1}</span><b>{item}</b>{i<items.length-1&&<i/>}</div>)}</nav>}

function EmployeeSearch({value,onChange,onSelect}:{value:string;onChange:(v:string)=>void;onSelect:(v:string)=>void}){const [focused,setFocused]=useState(false);const query=normalizeName(value);const suggestions=useMemo(()=>{if(query.length<2)return[];return EMPLOYEES.filter(name=>name.includes(query)).sort((a,b)=>a.localeCompare(b)).slice(0,8)},[query]);const show=focused&&suggestions.length>0;return <div className="employee-search"><Label htmlFor="surname">Employee</Label><Input id="surname" value={value} placeholder="Type at least 2 letters…" autoComplete="off" onFocus={()=>setFocused(true)} onChange={e=>onChange(e.target.value)} onKeyDown={e=>{if(e.key==="Escape")setFocused(false);if(e.key==="Enter"&&suggestions[0]){onSelect(suggestions[0]);setFocused(false)}}}/>{show&&<div className="suggestions" role="listbox">{suggestions.map(name=><button type="button" key={name} className="suggestion" onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(name);setFocused(false)}}><strong>{name}</strong><small>{ADMIN_SURNAME_ROLES[name]?"ADMIN":"Employee schedule"}</small></button>)}</div>}</div>}

function FileDrop({label,file,onFile}:{label:string;file:File|null;onFile:(f:File|null)=>void}){const[inputId]=useState(()=>`file-${Math.random().toString(36).slice(2)}`);const[dragging,setDragging]=useState(false);const accept=(f:File)=>{const ok=/\.(xlsx|xls|csv)$/i.test(f.name);if(ok)onFile(f)};return <div className={`drop ${dragging?"dragging":""} ${file?"has-file":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);const f=e.dataTransfer.files?.[0];if(f)accept(f)}} onClick={()=>document.getElementById(inputId)?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")document.getElementById(inputId)?.click()}}><div className="drop-icon">{file?"✓":"↑"}</div><div className="drop-copy"><b>{file?file.name:`Drop ${label.toLowerCase()} here`}</b><p>{file?`${(file.size/1024/1024).toFixed(2)} MB · Ready to process`:"Drag & drop or click to browse · XLSX, XLS, CSV"}</p></div>{file&&<Button variant="outline" size="sm" className="remove-file" onClick={e=>{e.stopPropagation();onFile(null)}}>Remove</Button>}<input id={inputId} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)accept(f);e.currentTarget.value=""}}/></div>}

function Status({kind}:{kind:CheckRow["status"]}){return <span className={`badge badge-${kind.toLowerCase()}`}>{kind}</span>}
function LoadingScreen(){return <div className="loading-screen" role="status" aria-live="polite"><div className="loading-card"><div className="loading-spinner"/><h2>Processing attendance</h2><p>We're working through your files. This may take a moment.</p><div className="loading-steps"><span>✓ Reading DTR and biometrics</span><span>✓ Matching employee</span><span>✓ Checking stored schedule</span><span>✓ Validating attendance</span></div><small>Please keep this tab open.</small></div></div>}

export function PayrollCheckerPage(){const[surname,setSurname]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[dtrFile,setDtrFile]=useState<File|null>(null),[bioFile,setBioFile]=useState<File|null>(null),[result,setResult]=useState<RunResult|null>(null),[error,setError]=useState<string|null>(null),[running,setRunning]=useState(false),[filter,setFilter]=useState("ALL"),[checks,setChecks]=useState<Record<string,boolean>>({});
 const normalizedSurname=normalizeName(surname);const databaseMatch=!!normalizedSurname&&(!!EMPLOYEE_SCHEDULES[normalizedSurname]||!!ADMIN_SURNAME_ROLES[normalizedSurname]);
 const currentStep=result?3:(dtrFile&&bioFile?2:(startDate&&endDate?1:0));
 const rows=useMemo(()=>{if(!result)return[];return result.rows.filter(r=>{const verified=(r.wfh&&checks[`wfh-${r.dateLabel}`])||(r.absent&&checks[`abs-${r.dateLabel}`]);if(filter==="ALL")return true;if(filter==="ISSUE")return r.hasIssue;if(filter==="WFH")return r.wfh;if(filter==="ABSENT")return r.absent;if(filter==="VERIFIED")return (!r.wfh&&!r.absent&&!r.hasIssue)||verified;if(filter==="UNVERIFIED")return (r.wfh||r.absent)&&!verified;return true})},[result,filter,checks]);
 const pendingVerification=result?result.rows.filter(r=>(r.wfh||r.absent)&&!(r.wfh?checks[`wfh-${r.dateLabel}`]:checks[`abs-${r.dateLabel}`])).length:0;
 async function handleRun(){setError(null);if(!surname.trim())return setError("Select an employee from the suggestions or enter a valid surname.");if(!databaseMatch)return setError("That employee is not in the stored database. Choose a name from the suggestions.");if(!dtrFile||!bioFile)return setError("Please upload both the DTR workbook and biometrics export.");if(!startDate||!endDate)return setError("Choose both a start date and an end date.");const from=new Date(`${startDate}T00:00:00`),to=new Date(`${endDate}T00:00:00`);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)return setError("The date range is invalid. Make sure the start date is not after the end date.");setRunning(true);try{const[dtr,bio]=await Promise.all([readWorkbookGrid(dtrFile),readWorkbookGrid(bioFile)]);const r=runCheck({dtrGrid:dtr,bioGrid:bio,surname,startDate:from,endDate:to});setResult(r);setChecks({});setFilter("ALL")}catch(e){setResult(null);setError(e instanceof Error?e.message:"We couldn't analyze the uploaded files. Check that they are valid DTR and biometrics exports and try again.")}finally{setRunning(false)}}
 function toggle(row:CheckRow){const key=`${row.wfh?"wfh":"abs"}-${row.dateLabel}`;setChecks(p=>({...p,[key]:!p[key]}))}
 function isVerified(row:CheckRow){return !row.hasIssue&&!row.wfh&&!row.absent||(row.wfh&&!!checks[`wfh-${row.dateLabel}`])||(row.absent&&!!checks[`abs-${row.dateLabel}`])}
 function exportFile(){if(!result||pendingVerification>0)return;const final={...result,rows:result.rows.map(r=>{const wfhVerified=r.wfh?!!checks[`wfh-${r.dateLabel}`]:false;const absentVerified=r.absent?!!checks[`abs-${r.dateLabel}`]:false;return {...r,wfhVerified,absentVerified,remarks:r.wfh?(wfhVerified?"WORK FROM HOME — VERIFIED":""):r.absent?(absentVerified?"ABSENT — VERIFIED":""):r.remarks}}).filter(r=>!r.wfh||r.wfhVerified).filter(r=>!r.absent||r.absentVerified)};downloadIssuesReport(final,`${result.employeeName.replace(/[^A-Z0-9, _-]/gi,"")||"EMPLOYEE"}_attendance.xlsx`)}
 const verifiedCount=result?result.rows.filter(isVerified).length:0;const unverifiedCount=result?result.rows.length-verifiedCount:0;const problems=result?result.rows.filter(r=>r.hasIssue||r.wfh||r.absent):[];
 return <main>{running&&<LoadingScreen/>}<header><div className="wrap"><small>ATTENDANCE AUDIT</small><h1>Payroll Checker</h1><p>Check attendance quickly and consistently using your DTR and biometrics files.</p></div></header><div className="wrap content"><Workflow step={currentStep}/>
 <section><div className="section-head"><div><h2>Employee & period</h2><p>{ADMIN_HINT}</p></div></div><div className="grid3"><div><EmployeeSearch value={surname} onChange={v=>{setSurname(v);setError(null)}} onSelect={v=>{setSurname(v);setError(null)}}/>{surname.trim()&&<div className={`database-status ${databaseMatch?"found":"not-found"}`}>{databaseMatch?<><span>✓</span> Employee found</>:<><span>!</span> Choose an employee from the database</>}</div>}</div><div><Label htmlFor="start">Start date</Label><Input id="start" type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);setError(null)}}/></div><div><Label htmlFor="end">End date</Label><Input id="end" type="date" value={endDate} onChange={e=>{setEndDate(e.target.value);setError(null)}}/></div></div></section>
 <section><div className="section-head"><div><h2>Upload files</h2><p>Drop your files into the boxes below, or click to browse.</p></div></div><div className="files"><FileDrop label="DTR workbook" file={dtrFile} onFile={f=>{setDtrFile(f);setError(null)}}/><FileDrop label="Biometrics export" file={bioFile} onFile={f=>{setBioFile(f);setError(null)}}/></div>{error&&<div className="error"><b>We couldn't continue</b><p>{error}</p><small>Fix the item above and try again.</small></div>}<div className="actions"><Button onClick={handleRun} disabled={running}>{running?<><span className="spinner"/>Analyzing…</>:"Analyze attendance"}</Button></div></section>
 {result&&<><section><div className="employee-card"><div><small>EMPLOYEE</small><h2>{result.employeeName}</h2><p>{result.role} · ID {result.employeeId??"Not found"}</p><p>{startDate} → {endDate}</p></div><div className="stats"><div><strong>{result.totalDays}</strong><span>DAYS</span></div><div><strong>{result.issueCount}</strong><span>ISSUES</span></div><div><strong>{result.wfhCount}</strong><span>WFH</span></div><div><strong>{result.absentCount}</strong><span>ABSENT</span></div></div></div></section>
 {problems.length>0&&<section className="problems"><div className="section-head"><div><h2>Problems found</h2><p>{problems.length} day{problems.length===1?"":"s"} need attention or confirmation.</p></div></div><div className="problem-list">{problems.slice(0,10).map((r,i)=><div className="problem" key={`${r.dateLabel}-${i}`}><span className="problem-mark">!</span><div><b>{r.dateLabel} · {r.actualWeekday}</b><p>{r.wfh?"Work from home":r.absent?"Absent":r.remarks||"Attendance issue detected"}</p></div><span className="problem-status">{r.wfh?"WFH":r.absent?"ABSENT":"ISSUE"}</span></div>)}</div>{problems.length>10&&<small>Showing the first 10 problems. Use the filters below to review all records.</small>}</section>}
 <section><div className="section-head"><div><h2>Attendance results</h2><p>Use the filters to focus on the days that matter.</p></div><Button variant="ghost" size="sm" onClick={()=>setFilter("ALL")}>Reset filters</Button></div><div className="filters">{[["ALL",result.rows.length],["ISSUE",result.issueCount],["WFH",result.wfhCount],["ABSENT",result.absentCount],["VERIFIED",verifiedCount],["UNVERIFIED",unverifiedCount]].map(([x,n])=><button key={x} className={filter===x?"filter active":"filter"} onClick={()=>setFilter(String(x))}>{x} <span>{n}</span></button>)}</div><div className="results"><table><thead><tr><th>Date</th><th>Day</th><th>Status</th><th>Issues / Remarks</th><th>Verify</th></tr></thead><tbody>{rows.map((r,i)=>{const checked=r.wfh?!!checks[`wfh-${r.dateLabel}`]:!!checks[`abs-${r.dateLabel}`];const remarks=r.wfh?`WORK FROM HOME — ${r.remarks||"No biometric attendance"}`:r.absent?`ABSENT — ${r.remarks||"No biometric attendance"}`:r.remarks;return <tr key={`${r.dateLabel}-${i}`} className={r.hasIssue||r.wfh||r.absent?"issue":""}><td>{r.dateLabel}</td><td>{r.actualWeekday}</td><td><Status kind={checked?"VERIFIED":r.status}/>{checked&&<span className="verified-mark">✓ Verified</span>}</td><td>{remarks}</td><td>{(r.wfh||r.absent)&&<label className="verify-control"><input className="verify-checkbox" type="checkbox" checked={checked} onChange={()=>toggle(r)}/><span>{checked?(r.wfh?"WFH confirmed":"Absence confirmed"):(r.wfh?"Confirm WFH":"Confirm absence")}</span></label>}</td></tr>})}</tbody></table>{!rows.length&&<p className="empty">No records for this filter.</p>}</div></section>
 <section className="export-section"><h2>Export</h2>{pendingVerification>0?<><p className="export-warning">⚠ Verify all WFH and ABSENT entries before exporting. <b>{pendingVerification}</b> verification{pendingVerification===1?"":"s"} remaining.</p><Button disabled>Export Excel</Button></>:<><p className="export-ready">✓ All WFH and ABSENT entries have been verified. The output can now be generated.</p><Button onClick={exportFile}>Export Excel</Button></>}</section></>}
 <footer>WFH and ABSENT entries appear in Issues / Remarks but are not added to the Excel output until the user verifies them. Export is locked until every WFH/ABSENT entry has been verified.</footer></div></main>}
