import { useMemo, useState } from "react";
import { Button } from "./components/ui/button";
import { Input } from "./components/ui/input";
import { Label } from "./components/ui/label";
import { Switch } from "./components/ui/switch";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "./components/ui/select";
import { DEFAULT_ADMIN_SCHEDULE,WEEKDAYS,runCheck,type CheckRow,type DailySchedule,type Grid,type RunResult,type Schedule,type ScheduleType,type Weekday } from "./lib/payroll/engine";
import { downloadIssuesReport,readWorkbookGrid } from "./lib/payroll/workbook";

const DESCRIPTION="Upload a DTR and a biometrics export to automatically flag late, undertime, absent and clock mismatches, then download an issues-only Excel report.";
type WeekdayForm=Record<Weekday,{enabled:boolean;start:string;end:string;type:ScheduleType}>;
const defaultForm:WeekdayForm=WEEKDAYS.reduce((a,d)=>{a[d]={enabled:true,start:"08:00",end:"17:00",type:"FULL DAY"};return a},{} as WeekdayForm);
function mins(v:string){const m=v.match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):null;}
function buildSchedule(f:WeekdayForm):Schedule{const s:Schedule={} as Schedule;for(const d of WEEKDAYS){const e=f[d],start=mins(e.start),end=mins(e.end);s[d]=e.enabled&&start!=null&&end!=null?({start,end,type:e.type} satisfies DailySchedule):null;}return s;}
function FileDrop({label,hint,file,onFile}:{label:string;hint:string;file:File|null;onFile:(f:File|null)=>void}){return <div className="drop"><div><b>{label}</b><p>{file?file.name:hint}</p></div><div>{file&&<Button variant="ghost" size="sm" onClick={()=>onFile(null)}>Clear</Button>}<Button variant="secondary" size="sm" onClick={()=>document.getElementById(`file-${label}`)?.click()}>Choose file</Button></div><input id={`file-${label}`} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>onFile(e.target.files?.[0]??null)}/></div>}
function Stat({value,label,red=false}:{value:string|number;label:string;red?:boolean}){return <div className="stat"><strong className={red?"red":""}>{value}</strong><span>{label}</span></div>}
function Row({row}:{row:CheckRow}){return <tr className={row.hasIssue?"issue":""}><td>{row.dateLabel}</td><td>{row.actualWeekday}</td><td>{row.remarks}</td></tr>}
export function PayrollCheckerPage(){
 const [surname,setSurname]=useState(""),[isAdmin,setIsAdmin]=useState(true),[form,setForm]=useState(defaultForm),[startDate,setStartDate]=useState("2026-06-26"),[endDate,setEndDate]=useState("2026-07-15"),[dtrFile,setDtrFile]=useState<File|null>(null),[bioFile,setBioFile]=useState<File|null>(null),[result,setResult]=useState<RunResult|null>(null),[error,setError]=useState<string|null>(null),[running,setRunning]=useState(false),[onlyIssues,setOnlyIssues]=useState(true);
 const visibleRows=useMemo(()=>result?(onlyIssues?result.rows.filter(r=>r.hasIssue):result.rows):[],[result,onlyIssues]);
 function updateDay(day:Weekday,patch:Partial<WeekdayForm[Weekday]>){setForm(p=>({...p,[day]:{...p[day],...patch}}))}
 async function handleRun(){setError(null);if(!surname.trim())return setError("Enter the employee surname.");if(!dtrFile||!bioFile)return setError("Both the DTR file and the biometrics file are required.");const from=new Date(`${startDate}T00:00:00`),to=new Date(`${endDate}T00:00:00`);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)return setError("Enter a valid date range.");setRunning(true);try{const [dtrGrid,bioGrid]:[Grid,Grid]=await Promise.all([readWorkbookGrid(dtrFile),readWorkbookGrid(bioFile)]);setResult(runCheck({dtrGrid,bioGrid,schedule:isAdmin?DEFAULT_ADMIN_SCHEDULE:buildSchedule(form),startDate:from,endDate:to}));}catch(e){setResult(null);setError(e instanceof Error?e.message:"Could not read the uploaded files.");}finally{setRunning(false)}}
 return <main><header><div className="wrap"><small>DTR × BIOMETRICS</small><h1>Payroll Checker</h1><p>{DESCRIPTION} Everything runs in your browser — no file ever leaves this device.</p></div></header><div className="wrap content">
 <section><h2>1. Employee & period</h2><div className="grid3"><div><Label htmlFor="surname">Employee surname</Label><Input id="surname" value={surname} maxLength={80} placeholder="Dela Cruz" onChange={e=>setSurname(e.target.value)}/></div><div><Label htmlFor="start">Start date</Label><Input id="start" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div><Label htmlFor="end">End date</Label><Input id="end" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div></div></section>
 <section><div className="section-head"><div><h2>2. Schedule</h2><p>{isAdmin?"Admin: 8:00 AM – 5:00 PM, Monday to Friday.":"Employee: set the working hours for each weekday."}</p></div><div className="switchline">Admin default <Switch checked={isAdmin} onCheckedChange={setIsAdmin} aria-label="Use admin schedule"/></div></div>{!isAdmin&&<div className="days">{WEEKDAYS.map(day=>{const e=form[day];return <div className="day" key={day}><div><Switch checked={e.enabled} onCheckedChange={v=>updateDay(day,{enabled:v})}/><span>{day}</span></div><Input type="time" disabled={!e.enabled} value={e.start} onChange={x=>updateDay(day,{start:x.target.value})}/><Input type="time" disabled={!e.enabled} value={e.end} onChange={x=>updateDay(day,{end:x.target.value})}/><Select value={e.type} disabled={!e.enabled} onValueChange={v=>updateDay(day,{type:v as ScheduleType})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="FULL DAY">Full day</SelectItem><SelectItem value="MORNING">Morning only</SelectItem><SelectItem value="AFTERNOON">Afternoon only</SelectItem></SelectContent></Select></div>})}</div>}</section>
 <section><h2>3. Files</h2><div className="files"><FileDrop label="DTR workbook" hint="Drop the .xlsx here (dates in column C, remarks column auto-detected)" file={dtrFile} onFile={setDtrFile}/><FileDrop label="Biometrics export" hint="Drop the .xlsx here (employee no., timestamp, C/In or C/Out)" file={bioFile} onFile={setBioFile}/></div>{error&&<p className="error">{error}</p>}<div className="actions"><Button onClick={handleRun} disabled={running}>{running?"Checking…":"Run check"}</Button>{result&&<Button variant="secondary" onClick={()=>downloadIssuesReport(result.rows,`${surname.trim().toUpperCase()||"EMPLOYEE"}_payroll_issues.xlsx`)}>Download issues report</Button>}</div></section>
 {result&&<section><div className="stats"><Stat value={result.totalDays} label="Days checked"/><Stat value={result.issueCount} label="Flagged days" red/><Stat value={result.totalDays-result.issueCount} label="Clean days"/><Stat value={result.employeeId??"—"} label="Employee no."/></div>{!result.remarksColumnFound&&<p className="warning">Warning: the DTR remarks column was not found, so payroll marks cannot be verified.</p>}<div className="results"><div className="section-head"><h2>Results for {surname.trim()||"employee"}</h2><label className="switchline"><Switch checked={onlyIssues} onCheckedChange={setOnlyIssues}/> Show flagged only</label></div>{visibleRows.length?<table><thead><tr><th>Date</th><th>Day</th><th>Issues / Remarks</th></tr></thead><tbody>{visibleRows.map((r,i)=><Row key={`${r.dateLabel}-${i}`} row={r}/>)}</tbody></table>:<p className="empty">No rows to show for this filter.</p>}</div></section>}
 <footer>Checks performed: DTR vs biometrics clock-in/out mismatches, late and undertime against the schedule, unmarked or wrongly marked LATE / U.T. / ABSENT, attendance on NO WORK days, and missing biometric taps.</footer>
 </div></main>
}